### ISSUE TITLE
Run sample error

### ISSUE THREAD

**Issue by sikoushixinyou** [mimicji/FlowMatrix#2]
Hi！
When I run the example, I meet this problem.
How should I go about getting a useful database？
![QIJ)B~ NF}Q@VH1TOZP_%E1](https://user-images.githubusercontent.com/62183661/205011011-37ef19ea-d8ea-45f9-8496-3a239108dd69.png)

**Comment by mimicji** [comment]
Hi,

You may find the database with 2 examples from the [release](https://github.com/mimicji/FlowMatrix/releases/download/ExampleDB/examples.db) (I just published).

Thanks,
Kaihang
