### ISSUE TITLE
How to use FlowMatrix in virtual machine？

### ISSUE THREAD

**Issue by sikoushixinyou** [mimicji/FlowMatrix#3]
I tried to configure this project on vmware workstations and got the following error：

![CGDX5 8Z9R5((X2I68`GOWA](https://user-images.githubusercontent.com/62183661/205045751-860cc679-3231-4155-9278-d2f77092dc3e.png)

Is it because the Nvidia GPU cannot be used in the virtual machine?
Does this FlowMatrix project must require a GPU to run normally? Can it support the CPU version？

**Comment by mimicji** [comment]
Hi,

I am afraid it is impossible to run FlowMatrix in a VM.
It is possible to compile CUDA code in a virtual machine. But, to my best knowledge, there is no existing virtual machine that supports running environments of CUDA code for now. I would suggest you use dual-booting or WSL (if you are using Windows as your main OS).
As FlowMatrix is a GPU-based project, we do not have a plan to release a CPU version. If you wish to do so, you may replace the [FMCuSparseLinAlg](https://github.com/mimicji/FlowMatrix/tree/main/FMCuSparseLinAlg) component with your own CPU version, which supports CPU-based sparse linear algebra operations.

Thanks,
Kaihang
