### ISSUE TITLE
How to build my own flow matrix information database？

### ISSUE THREAD

**Issue by sikoushixinyou** [mimicji/FlowMatrix#4]
Hi！Can you answer my doubts？ Thank you very much！
The db file contains the flow matrix information corresponding to the binary program. If I want to generate a corresponding db file for my binary program, how should I build it.
And whether the instruction flow matrix information of the db file of a binary program can be multiplexed to multiple binary programs with the same instruction.

**Comment by mimicji** [comment]
Hi,

FlowMatrix is an offline DIFT tool. It requires:
1) Execution traces. In particular, any instruction traces that can be converted into FMtrace format will be applied. You may need to implement your own trace convertor.
2) DIFT propagation rules. Any DIFT propagation rules that are defined as [acorns_obj.proto](https://github.com/mimicji/FlowMatrix/blob/main/libFlowMatrix/src/acorns_obj.proto) will be accepted. In experiments, we use [TaintInduce](https://taintinduce.github.io/) to generate those rules automatically. 

Once you have all of these, you may run ./bin/TraceLoader to load your trace into the database.

Thanks,
Kaihang

**Comment by sikoushixinyou** [comment]
So I first need to implement a converter to convert the instructions of the binary program I want to monitor into the result of the FMtrace format.Then I need to generate the taint propagation rules for the corresponding instructions, and express these rules in an acceptable format.
I also tried using TaintInduce，but about TaintInduce I can't open the url:'http://kentridge.d2.comp.nus.edu.sg:8000/'
