### ISSUE TITLE
Cannot find TaintInduce online

### ISSUE THREAD

**Issue by seifkosbar** [mimicji/FlowMatrix#6]
Hi,

I cannot seem to find any library named TaintInduce other than [this one](https://github.com/melynx/taintinduce). It is a python package and some of its dependencies is not found online too (like squirrel-framework). Could you please provide a link for the TaintInduce library that you used?

**Comment by mimicji** [comment]
Please email TaintInduce's authors for access.

**Comment by you-tianle** [comment]
> Hi,
> 
> I cannot seem to find any library named TaintInduce other than [this one](https://github.com/melynx/taintinduce). It is a python package and some of its dependencies is not found online too (like squirrel-framework). Could you please provide a link for the TaintInduce library that you used?

Hello, did you figure out the problem about squirrel-framework?
